name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  podspec:
    runs-on: macos-12
    name: CocoaPods Lint
    env:
      DEVELOPER_DIR: "/Applications/Xcode_13.4.1.app/Contents/Developer"
    steps:
      - uses: actions/checkout@v2
      - run: pod lib lint --allow-warnings

  xcode:
    name: ${{ matrix.xcode }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_14.0.1"
            runsOn: macOS-12
            name: "macOS 12, Xcode 14.0.1, Swift 5.7"
          - xcode: "Xcode_13.4.1"
            runsOn: macOS-12
            name: "macOS 12, Xcode 13.4.1, Swift 5.6.1"
          - xcode: "Xcode_12.5.1"
            runsOn: macOS-11
            name: "macOS 11, Xcode 12.5.1, Swift 5.4.2"
          - xcode: "Xcode_12"
            runsOn: macOS-10.15
            name: "macOS 10.15, Xcode 12.0.1, Swift 5.3"
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 2
      - name: ${{ matrix.name }}
        run: |
          set -o pipefail
          xcodebuild build-for-testing test-without-building -workspace APIKit.xcworkspace -scheme APIKit | xcpretty -c
          xcodebuild build-for-testing test-without-building -workspace APIKit.xcworkspace -scheme APIKit -sdk iphonesimulator -destination "name=iPhone 8" | xcpretty -c
          xcodebuild build-for-testing test-without-building -workspace APIKit.xcworkspace -scheme APIKit -sdk appletvsimulator -destination "name=Apple TV" | xcpretty -c
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.2.1
        if: ${{ success() }}

  swiftpm:
    name: SPM with ${{ matrix.xcode }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_14.0.1"
            runsOn: macOS-12
            name: "macOS 12, Xcode 14.0.1, Swift 5.7"
            action: swift test -c debug
          - xcode: "Xcode_13.4.1"
            runsOn: macOS-12
            name: "macOS 12, Xcode 13.4.1, Swift 5.6.1"
            action: swift test -c debug
          - xcode: "Xcode_12.5.1"
            runsOn: macOS-11
            name: "macOS 11, Xcode 12.5.1, Swift 5.4.2"
            action: swift test -c debug
          - xcode: "Xcode_12"
            runsOn: macOS-10.15
            name: "macOS 10.15, Xcode 12.0.1, Swift 5.3"
            action: swift build -c debug
    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.name }}
        run: ${{ matrix.action }}
